import type { Locale } from "@/lib/dictionaries";

const copy = {
  en: {
    portalTitle: "Advocate Portal",
    queueTitle: "Legacy review queue",
    queueSubtitle:
      "Pre-packaged briefs from elders — review, verify titles, draft, and seal.",
    openCases: "Open cases",
    myCases: "Assigned to me",
    completed: "Completed",
    emptyQueue: "No review requests yet. Elders submit from their vault.",
    assign: "Claim case",
    openCase: "Open case",
    caseBrief: "Client brief",
    assets: "Assets",
    heirs: "Heirs",
    allocations: "Allocations",
    checklist: "Verification checklist",
    saveChecklist: "Save checklist",
    consult: "Consultation",
    scheduleConsult: "Save schedule",
    legalDocs: "Legal documents",
    addDoc: "Add document draft",
    docTypes: {
      will: "Will",
      land_trust: "Land / Family Trust",
      poa: "Power of Attorney",
    },
    titleLookup: "ArdhiSasa title lookup",
    runLookup: "Run simulated lookup",
    lookupHint:
      "Simulated Ministry of Lands search for demos. Replace with live ArdhiSasa credentials later.",
    eSign: "E-sign & certify",
    signatureName: "Typed full name (e-signature)",
    certifyUpload: "Upload certified PDF / scan (optional)",
    sealVault: "Seal vault & complete case",
    sealHint:
      "Requires checklist complete and at least one signed or certified document.",
    logout: "Sign out",
    welcome: "Counsel",
    backQueue: "Back to queue",
    status: "Status",
    package: "Package",
    consultMode: "Consult mode",
    notes: "Client notes",
    simulated: "Simulated",
    found: "Found",
    notFound: "Not found",
    sealedDocs: "Certified documents in vault",
  },
  sw: {
    portalTitle: "Portal ya Mawakili",
    queueTitle: "Foleni ya ukaguzi wa urithi",
    queueSubtitle:
      "Maelezo yaliyoandaliwa na wazee — kagua, thibitisha hati, andika, na tia muhuri.",
    openCases: "Kesi wazi",
    myCases: "Niliyopewa",
    completed: "Zimekamilika",
    emptyQueue: "Hakuna maombi bado. Wazee wanawasilisha kutoka hifadhi yao.",
    assign: "Chukua kesi",
    openCase: "Fungua kesi",
    caseBrief: "Muhtasari wa mteja",
    assets: "Mali",
    heirs: "Warithi",
    allocations: "Ugawaji",
    checklist: "Orodha ya uthibitisho",
    saveChecklist: "Hifadhi orodha",
    consult: "Ushauri",
    scheduleConsult: "Hifadhi ratiba",
    legalDocs: "Nyaraka za kisheria",
    addDoc: "Ongeza rasimu",
    docTypes: {
      will: "Wosia",
      land_trust: "Amana ya Ardhi / Familia",
      poa: "Uwakilishi wa Nguvu",
    },
    titleLookup: "Utafutaji wa hati (ArdhiSasa)",
    runLookup: "Endesha utafutaji wa majaribio",
    lookupHint:
      "Utafutaji wa majaribio wa Wizara ya Ardhi. Badilisha na ArdhiSasa halisi baadaye.",
    eSign: "Saini kidijitali & thibitisha",
    signatureName: "Jina kamili (sahihi ya kidijitali)",
    certifyUpload: "Pakia PDF / skani iliyothibitishwa (si lazima)",
    sealVault: "Funga hifadhi & kamilisha kesi",
    sealHint:
      "Inahitaji orodha kamili na angalau hati moja iliyosainiwa au kuthibitishwa.",
    logout: "Toka",
    welcome: "Wakili",
    backQueue: "Rudi foleni",
    status: "Hali",
    package: "Kifurushi",
    consultMode: "Njia ya ushauri",
    notes: "Maelezo ya mteja",
    simulated: "Majaribio",
    found: "Imepatikana",
    notFound: "Haijapatikana",
    sealedDocs: "Nyaraka zilizothibitishwa kwenye hifadhi",
  },
} as const;

export function advocateCopy(locale: Locale) {
  return copy[locale];
}
