import type { Locale } from "@/lib/dictionaries";

const copy = {
  en: {
    portalTitle: "Advocate Portal",
    queueTitle: "Legacy review queue",
    queueSubtitle:
      "Pre-packaged briefs from elders — review, verify titles, draft, and seal.",
    matchedCases: "Matched to you",
    matchedHint:
      "Automatically routed because you practise in the counties where this estate's land sits. First to claim takes the case.",
    matchedBadge: "County match",
    openCases: "Open cases",
    myCases: "Assigned to me",
    completed: "Completed",
    testaments: "Voice testaments",
    noTestaments: "The elder has not recorded a spoken statement.",
    stamp: "Legal stamp",
    stampHint:
      "Stamp the instrument with your practising number before you e-sign it. The reference is recorded against the case for chain of custody.",
    stampCounty: "Registry / county of execution",
    stampNotes: "Stamp annotation",
    applyStamp: "Apply legal stamp",
    stamped: "Stamped",
    notStamped: "Not stamped",
    stampRequired: "Stamp this document before e-signing.",
    emptyQueue: "No review requests yet. Elders submit from their vault.",
    assign: "Claim case",
    openCase: "Open case",
    caseBrief: "Client brief",
    assets: "Assets",
    heirs: "Heirs",
    allocations: "Allocations",
    checklist: "Verification checklist",
    saveChecklist: "Save checklist",
    consult: "Consultation",
    scheduleConsult: "Save schedule",
    legalDocs: "Legal documents",
    addDoc: "Add document draft",
    docTypes: {
      will: "Will",
      land_trust: "Land / Family Trust",
      poa: "Power of Attorney",
    },
    titleLookup: "ArdhiSasa title lookup",
    runLookup: "Run simulated lookup",
    lookupHint:
      "Simulated Ministry of Lands search for demos. Replace with live ArdhiSasa credentials later.",
    eSign: "E-sign & certify",
    signatureName: "Typed full name (e-signature)",
    certifyUpload: "Upload certified PDF / scan (optional)",
    sealVault: "Seal vault & complete case",
    sealHint:
      "Requires checklist complete and at least one signed or certified document.",
    logout: "Sign out",
    welcome: "Counsel",
    backQueue: "Back to queue",
    status: "Status",
    package: "Package",
    consultMode: "Consult mode",
    notes: "Client notes",
    simulated: "Simulated",
    found: "Found",
    notFound: "Not found",
    sealedDocs: "Certified documents in vault",
  },
  sw: {
    portalTitle: "Portal ya Mawakili",
    queueTitle: "Foleni ya ukaguzi wa urithi",
    queueSubtitle:
      "Maelezo yaliyoandaliwa na wazee — kagua, thibitisha hati, andika, na tia muhuri.",
    matchedCases: "Zimelinganishwa nawe",
    matchedHint:
      "Zimepelekwa kwako kiotomatiki kwa sababu unafanya kazi katika kaunti ambako ardhi ya mali hii iko. Wa kwanza kuchukua ndiye anayepata kesi.",
    matchedBadge: "Ulinganifu wa kaunti",
    openCases: "Kesi wazi",
    myCases: "Niliyopewa",
    completed: "Zimekamilika",
    testaments: "Wosia wa sauti",
    noTestaments: "Mzee hajarekodi taarifa ya sauti.",
    stamp: "Muhuri wa kisheria",
    stampHint:
      "Tia muhuri hati kwa nambari yako ya leseni kabla ya kusaini kidijitali. Kumbukumbu ya muhuri huhifadhiwa kwenye kesi.",
    stampCounty: "Kaunti / ofisi ya usajili",
    stampNotes: "Maelezo ya muhuri",
    applyStamp: "Tia muhuri wa kisheria",
    stamped: "Imetiwa muhuri",
    notStamped: "Haijatiwa muhuri",
    stampRequired: "Tia muhuri hati kabla ya kusaini.",
    emptyQueue: "Hakuna maombi bado. Wazee wanawasilisha kutoka hifadhi yao.",
    assign: "Chukua kesi",
    openCase: "Fungua kesi",
    caseBrief: "Muhtasari wa mteja",
    assets: "Mali",
    heirs: "Warithi",
    allocations: "Ugawaji",
    checklist: "Orodha ya uthibitisho",
    saveChecklist: "Hifadhi orodha",
    consult: "Ushauri",
    scheduleConsult: "Hifadhi ratiba",
    legalDocs: "Nyaraka za kisheria",
    addDoc: "Ongeza rasimu",
    docTypes: {
      will: "Wosia",
      land_trust: "Amana ya Ardhi / Familia",
      poa: "Uwakilishi wa Nguvu",
    },
    titleLookup: "Utafutaji wa hati (ArdhiSasa)",
    runLookup: "Endesha utafutaji wa majaribio",
    lookupHint:
      "Utafutaji wa majaribio wa Wizara ya Ardhi. Badilisha na ArdhiSasa halisi baadaye.",
    eSign: "Saini kidijitali & thibitisha",
    signatureName: "Jina kamili (sahihi ya kidijitali)",
    certifyUpload: "Pakia PDF / skani iliyothibitishwa (si lazima)",
    sealVault: "Funga hifadhi & kamilisha kesi",
    sealHint:
      "Inahitaji orodha kamili na angalau hati moja iliyosainiwa au kuthibitishwa.",
    logout: "Toka",
    welcome: "Wakili",
    backQueue: "Rudi foleni",
    status: "Hali",
    package: "Kifurushi",
    consultMode: "Njia ya ushauri",
    notes: "Maelezo ya mteja",
    simulated: "Majaribio",
    found: "Imepatikana",
    notFound: "Haijapatikana",
    sealedDocs: "Nyaraka zilizothibitishwa kwenye hifadhi",
  },
} as const;

export function advocateCopy(locale: Locale) {
  return copy[locale];
}
