import type { Locale } from "@/lib/dictionaries";

const copy = {
  en: {
    loginTitle: "Open your Shamba Vault",
    loginSubtitle:
      "Sign in with your Kenyan phone number or email. We send a 6-digit code — no password.",
    loginIdentifierLabel: "Phone or email",
    loginIdentifierPlaceholder: "+2547… or name@email.com",
    loginIdentifierHint:
      "Codes always go to the phone on your account. Email is only for finding your account.",
    phoneLabel: "Phone number",
    emailLabel: "Email",
    emailHint: "Optional — you can use it later to sign in.",
    optional: "optional",
    nameLabel: "Full name (as on your ID)",
    addressLabel: "Home address / location",
    addressPlaceholder: "Village, estate, or street — enough for your advocate to reach you",
    countyLabel: "County",
    idFrontLabel: "National ID — front",
    idBackLabel: "National ID — back",
    signupTitle: "Create your ShambaTrust account",
    signupSubtitle:
      "One-time setup: phone, ID, and where you live. After this, you only verify with a code.",
    signupIdHint:
      "Clear photos or scans of both sides of your Kenyan national ID. JPG, PNG, WebP, or PDF under 8MB.",
    signupVerify: "Verify & open vault",
    roleLabel: "I am signing up as",
    roleElder: "Elder / Vault owner",
    roleAgent: "Family helper (Agent Mode)",
    roleAdvocate: "Partner advocate (LSK)",
    sendCode: "Send code",
    verify: "Verify & continue",
    sealedDocs: "Certified legal documents",
    emptySealedDocs: "No sealed documents yet. They appear after advocate sign-off.",
    codeLabel: "6-digit code",
    devHint: "Development mode code",
    backHome: "Back to home",
    vault: "My Vault",
    assets: "Assets",
    heirs: "Heirs",
    agent: "Agent Mode",
    review: "Legal review",
    execution: "Execution",
    succession: "Succession",
    logout: "Sign out",
    welcome: "Welcome",
    agentBadge: "Helping as family agent",
    ownerBadge: "Vault owner",
    status: "Vault status",
    addAsset: "Add asset",
    addHeir: "Add heir",
    addAnotherAsset: "Add another asset",
    addAnotherHeir: "Add another heir",
    continueHeirs: "Continue to heirs",
    continueAllocate: "Continue to allocate",
    continueReview: "Continue to legal review",
    save: "Save",
    delete: "Delete",
    emptyAssets: "No assets yet. Start by cataloguing a shamba or title deed.",
    emptyHeirs: "No heirs yet. Add children or beneficiaries clearly.",
    draftBanner: "Draft — free to edit. You are only charged when you submit for legal review.",
    submittedBanner:
      "Submitted — package in review. Assets, heirs, and allocations are locked.",
    amendmentBanner:
      "Amendment open — add missing assets, then resubmit for advocate review.",
    requestAmendment: "Request amendment",
    amendmentReasonLabel: "What do you need to add or change?",
    amendmentReasonPlaceholder:
      "e.g. Add 2 more shambas, Equity bank account, and the family Toyota",
    amendmentFreeHint:
      "Free to reopen within 48 hours of your last submit. After that, an amendment fee applies.",
    amendmentPaidHint:
      "The free 48-hour window has ended. Requesting an amendment will apply an amendment fee (not a full new package).",
    resubmitAmendment: "Resubmit amendment for review",
    wizardTitle: "Vault setup",
    stepAssets: "1. Catalog assets",
    stepHeirs: "2. Name heirs",
    stepAllocate: "3. Allocate",
    stepReview: "4. Submit legal review",
    assetTypes: {
      land: "Land / Shamba",
      commercial_plot: "Commercial plot",
      business: "Family business",
      vehicle: "Vehicle",
      bank_account: "Bank account",
      other: "Other",
    },
    reviewTitle: "Request legal verification",
    reviewSubtitle:
      "When your assets, heirs, and allocations are ready, submit for a partner advocate. This is the billable step.",
    submitReview: "Submit for advocate review",
    inviteAgent: "Invite family helper",
    inviteHint:
      "A tech-savvy son or daughter can help fill forms. They cannot finalize heir changes without your OTP.",
  },
  sw: {
    loginTitle: "Fungua Hifadhi yako ya Shamba",
    loginSubtitle:
      "Ingia kwa nambari ya simu au barua pepe. Tutakutumia msimbo wa tarakimu 6 — hakuna nenosiri.",
    loginIdentifierLabel: "Simu au barua pepe",
    loginIdentifierPlaceholder: "+2547… au name@email.com",
    loginIdentifierHint:
      "Misimbo hutumwa kwa simu iliyosajiliwa. Barua pepe hutumika kutafuta akaunti yako.",
    phoneLabel: "Nambari ya simu",
    emailLabel: "Barua pepe",
    emailHint: "Si lazima — unaweza kuitumia baadaye kuingia.",
    optional: "si lazima",
    nameLabel: "Jina kamili (kama kwenye kitambulisho)",
    addressLabel: "Anwani / mahali unapoishi",
    addressPlaceholder: "Kijiji, estate, au mtaa — kwa mawasiliano ya wakili",
    countyLabel: "Kaunti",
    idFrontLabel: "Kitambulisho — mbele",
    idBackLabel: "Kitambulisho — nyuma",
    signupTitle: "Unda akaunti ya ShambaTrust",
    signupSubtitle:
      "Usajili mara moja: simu, kitambulisho, na anwani. Baadaye unathibitisha kwa msimbo tu.",
    signupIdHint:
      "Picha au skani wazi za pande zote za kitambulisho cha Kenya. JPG, PNG, WebP, au PDF chini ya 8MB.",
    signupVerify: "Thibitisha & fungua hifadhi",
    roleLabel: "Ninasajili kama",
    roleElder: "Mzee / Mmiliki wa hifadhi",
    roleAgent: "Msaidizi wa familia (Hali ya Wakala)",
    roleAdvocate: "Wakili mshirika (LSK)",
    sendCode: "Tuma msimbo",
    verify: "Thibitisha & endelea",
    sealedDocs: "Nyaraka za kisheria zilizothibitishwa",
    emptySealedDocs: "Hakuna nyaraka bado. Zitaonekana baada ya sahihi ya wakili.",
    codeLabel: "Msimbo wa tarakimu 6",
    devHint: "Msimbo wa hali ya majaribio",
    backHome: "Rudi nyumbani",
    vault: "Hifadhi Yangu",
    assets: "Mali",
    heirs: "Warithi",
    agent: "Hali ya Wakala",
    review: "Ukaguzi wa kisheria",
    execution: "Utekelezaji",
    succession: "Mirathi",
    logout: "Toka",
    welcome: "Karibu",
    agentBadge: "Unasaidia kama wakala wa familia",
    ownerBadge: "Mmiliki wa hifadhi",
    status: "Hali ya hifadhi",
    addAsset: "Ongeza mali",
    addHeir: "Ongeza mrithi",
    addAnotherAsset: "Ongeza mali nyingine",
    addAnotherHeir: "Ongeza mrithi mwingine",
    continueHeirs: "Endelea kwa warithi",
    continueAllocate: "Endelea kwa ugawaji",
    continueReview: "Endelea kwa ukaguzi wa kisheria",
    save: "Hifadhi",
    delete: "Futa",
    emptyAssets: "Hakuna mali bado. Anza kwa kuorodhesha shamba au hati miliki.",
    emptyHeirs: "Hakuna warithi bado. Ongeza watoto au wanufaika wazi.",
    draftBanner:
      "Rasimu — unaweza kuhariri bure. Utatozwa tu unapowasilisha kwa ukaguzi wa kisheria.",
    submittedBanner:
      "Imewasilishwa — kifurushi kiko katika ukaguzi. Mali, warithi, na ugawaji zimefungwa.",
    amendmentBanner:
      "Marekebisho yamefunguliwa — ongeza mali zilizokosekana, kisha wasilisha tena kwa wakili.",
    requestAmendment: "Omba marekebisho",
    amendmentReasonLabel: "Unahitaji kuongeza au kubadilisha nini?",
    amendmentReasonPlaceholder:
      "mf. Ongeza mashamba 2, akaunti ya Equity, na Toyota ya familia",
    amendmentFreeHint:
      "Unaweza kufungua bure ndani ya saa 48 baada ya kuwasilisha. Baadaye ada ya marekebisho inatumika.",
    amendmentPaidHint:
      "Dirisha la bure la saa 48 limeisha. Kuomba marekebisho kutatoza ada ya marekebisho (si kifurushi kipya kamili).",
    resubmitAmendment: "Wasilisha tena marekebisho kwa ukaguzi",
    wizardTitle: "Usanidi wa hifadhi",
    stepAssets: "1. Orodhesha mali",
    stepHeirs: "2. Taja warithi",
    stepAllocate: "3. Gawanya",
    stepReview: "4. Wasilisha ukaguzi",
    assetTypes: {
      land: "Ardhi / Shamba",
      commercial_plot: "Kiwanja cha biashara",
      business: "Biashara ya familia",
      vehicle: "Gari",
      bank_account: "Akaunti ya benki",
      other: "Nyingine",
    },
    reviewTitle: "Omba uthibitisho wa kisheria",
    reviewSubtitle:
      "Mali, warithi, na ugawaji vikiwa tayari, wasilisha kwa wakili mshirika. Hii ndiyo hatua inayotozwa.",
    submitReview: "Wasilisha kwa ukaguzi wa wakili",
    inviteAgent: "Alika msaidizi wa familia",
    inviteHint:
      "Mwana au binti anayejua teknolojia anaweza kusaidia kujaza fomu. Hawezi kukamilisha mabadiliko ya warithi bila OTP yako.",
  },
} as const;

export function vaultCopy(locale: Locale) {
  return copy[locale];
}
